export const commentsConstants = {
  GET_COMMENTS: 'GET_COMMENTS',
  SET_COMMENTS: 'SET_COMMENTS',
  EDIT_COMMENT_BY_ID: 'EDIT_COMMENT_BY_ID',
  SET_EDITED_COMMENT: 'SET_EDITED_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  SET_DELETED_COMMENT: 'SET_DELETED_COMMENT',
}