export const postsConstants = {
  GET_POSTS: 'GET_POSTS',
  SET_POSTS: 'SET_POSTS',
  ADD_POST: 'ADD_POST',
  SET_ADDED_POST: 'SET_ADDED_POST',
  EDIT_POST_BY_ID: 'EDIT_POST_BY_ID',
  SET_EDITED_POST: 'SET_EDITED_POST',
  DELETE_POST: 'DELETE_POST',
  SET_DELETED_POST: 'SET_DELETED_POST',
}

