export enum GET_COMMENTS_FROM_POST {
  REQUEST = 'comments/GET_COMMENTS_FROM_POST_REQUEST',
  SUCCESS = 'comments/GET_COMMENTS_FROM_POST_SUCCESS',
  FAILURE = 'comments/GET_COMMENTS_FROM_POST_FAILURE',
  ADD = 'comments/GET_COMMENTS_FROM_POST_ADD',
}

export enum CREATE_COMMENT {
  REQUEST = 'comments/CREATE_COMMENT_REQUEST',
  SUCCESS = 'comments/CREATE_COMMENT_SUCCESS',
  FAILURE = 'comments/CREATE_COMMENT_FAILURE',
}
