export enum POSTS_TYPES {
	FETCHING_POSTS = '@post/FETCHING_POSTS',
	FILTER_POSTS = '@post/FILTER_POSTS',
	FETCHED_POSTS = '@post/FETCHED_POSTS',
	FETCHED_POSTS_ERRROR = '@post/FETCHED_POSTS_ERRROR',
	FETCHING_COMMENTS_BY_POST = '@post/FETCHING_COMMENTS_BY_POST',
	FETCHED_COMMENTS_BY_POST = '@post/FETCHED_COMMENTS_BY_POST',
	FETCHED_COMMENTS_BY_POST_ERROR = '@post/FETCHED_COMMENTS_BY_POST_ERROR',
	CLEAR_COMMENTS = '@post/CLEAR_COMMENTS',
}
